version: "3"

services:
  client:
    build: ./client
    ports:
      - 127.0.0.100:8080:8080
    volumes:
      - ./client:/data
    environment:
      - VUE_APP_API=rest
    networks:
      - proxy_net

  server:
    build: ./server
    ports:
      - 3000
    volumes:
      - ./server:/data
    depends_on: 
      - server-database
    environment:
      - CONNECTION_STRING=mongodb://server-database:27017/the-masquerade
      - ORIGIN=localhost
      - PROTOCOL=http
    networks:
      - proxy_net
    
  server-database:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
    networks:
      - proxy_net
      
  proxy: 
    image: nginx 
    volumes: # mount custom config at runtime 
      - ./nginx.conf:/etc/nginx/conf.d/default.conf 
    links:
    - client:client # "app" is the hostname used in proxy_pass directive
    - server:server # "app" is the hostname used in proxy_pass directive
    ports: 
      - 80:80 
    networks:
      - proxy_net
networks:
  proxy_net:
    driver: bridge

    